["us-deployment/Notifier"]
rabbitmq_address    = "35.239.225.192"
rabbitmq_port       = "5673"
rabbitmq_user    = "admin"
rabbitmq_password       = "admin"

["us-deployment/PostStorageUs"]
redis_address       = "35.239.225.192"
redis_port          = "6381"
redis_password          = ""


[serviceweaver]
binary = "./us-deployment"

[single]
listeners.postnot = {address = "0.0.0.0:12346"}

[multi]
listeners.postnot = {address = "0.0.0.0:12346"}

[gke]
regions = ["us-west4"]
