["eu-deployment/Notifier"]
rabbitmq_address    = "34.65.60.146"
rabbitmq_port       = "5672"
rabbitmq_user    = "admin"
rabbitmq_password       = "admin"

["eu-deployment/PostStorageEu"]
mysql_address       = "34.65.60.146"
mysql_port          = "3307"
mysql_password          = "root_password"
mysql_user          = "root"
mysql_datastore          = "post_notification"


[serviceweaver]
binary = "./eu-deployment"

[single]
listeners.postnot = {address = "0.0.0.0:12345"}

[multi]
listeners.postnot = {address = "0.0.0.0:12345"}


[gke]
regions = ["europe-west6"]
listeners.postnot = {public_hostname = "hello.com"}
