["eu_deployment/Notifier"]
rabbitmq_address = "35.198.175.8"
rabbitmq_port = "5672"
rabbitmq_user = "guest"
rabbitmq_password = "guest"

["eu_deployment/Post_storage_europe"]
redis_address = "35.198.175.8"
redis_port = "6379"
redis_password = ""

[serviceweaver]
binary = "./eu_deployment"

[gke]
regions = [ "europe-west6",]

[single.listeners.post_notification]
address = "0.0.0.0:12345"

[multi.listeners.post_notification]
address = "0.0.0.0:12345"

[gke.listeners.post_notification]
public_hostname = "hello.com"
