[serviceweaver]
binary = "./us-deployment"

[single]
listeners.postnot = {address = "0.0.0.0:12346"}
antipodeAgents.client = {datastoreType = "MySQL", host = "127.0.0.1", port = "3308", user = "root", password = "root_password", datastore = "post_notification"}
antipodeAgents.clientRabbitMQ = {datastoreType = "RabbitMQ", host = "localhost", port = "5673", user = "admin", password = "admin", datastore = "rabbitMQ"}

[multi]
listeners.postnot = {address = "0.0.0.0:12346"}
antipodeAgents.client = {datastoreType = "MySQL", host = "127.0.0.1", port = "3308", user = "root", password = "root_password", datastore = "post_notification"}
antipodeAgents.clientRabbitMQ = {datastoreType = "RabbitMQ", host = "localhost", port = "5673", user = "admin", password = "admin", datastore = "rabbitMQ"}

[gke]
regions = ["us-west4"]
listeners.postnot = {public_hostname = "hello.com"}