app_folder_name: trainticket
base_dir: /home/tmalhadas/XCWeaver/tese/weaver/trainticket
deployment_type: gcp
duration: '300'
rate: '100'
stack: trainticket
threads: '10'
workload_timestamp: 2024-09-05_15:11:16
