["trainticket/pkg/services/UserService"]
mongodb_address = "35.242.233.11"
mongodb_port = "27017"

["trainticket/pkg/services/AuthService"]
mongodb_address = "35.242.233.11"
mongodb_port = "27018"

["trainticket/pkg/services/TrainService"]
mongodb_address = "35.242.233.11"
mongodb_port = "27019"

["trainticket/pkg/services/PriceService"]
mongodb_address = "35.242.233.11"
mongodb_port = "27020"

["trainticket/pkg/services/OrderOtherService"]
mongodb_address = "35.242.233.11"
mongodb_port = "27021"

["trainticket/pkg/services/OrderService"]
mongodb_address = "35.242.233.11"
mongodb_port = "27021"

["trainticket/pkg/services/PaymentService"]
mongodb_address = "35.242.233.11"
mongodb_port = "27022"

["trainticket/pkg/services/InsidePaymentService"]
mongodb_address = "35.242.233.11"
mongodb_port = "27023"

["trainticket/pkg/services/ContactsService"]
mongodb_address = "35.242.233.11"
mongodb_port = "27024"

["trainticket/pkg/services/CancelService"]
uptrace_dns = "http://project2_secret_token@localhost:14318?grpc=14317"

[serviceweaver]
binary = "./trainticket"

[gke]
regions = [ "europe-west3",]

[single.listeners.wrk2]
address = "0.0.0.0:12345"

[multi.listeners.wrk2]
address = "0.0.0.0:12345"

[gke.listeners.wrk2]
public_hostname = "weaver.trainticket.eu"
