["us_deployment/Notifier"]
rabbitmq_address    = "localhost"
rabbitmq_port       = "5672"
rabbitmq_user    = "admin"
rabbitmq_password       = "admin"

["us_deployment/Post_storage_america"]
mongo_address       = "localhost"
mongo_port          = "27018"


[serviceweaver]
binary = "./us_deployment"

[single]
listeners.post_notification = {address = "0.0.0.0:12346"}

[multi]
listeners.post_notification = {address = "0.0.0.0:12346"}

[gke]
regions = ["us-west4"]
