["us-deployment/Notifier"]
rabbitmq_address    = "34.121.3.58"
rabbitmq_port       = "5673"
rabbitmq_user    = "admin"
rabbitmq_password       = "admin"

["us-deployment/PostStorageUs"]
mongo_address       = "34.121.3.58"
mongo_port          = "27018"


[serviceweaver]
binary = "./us-deployment"

[single]
listeners.postnot = {address = "0.0.0.0:12346"}

[multi]
listeners.postnot = {address = "0.0.0.0:12346"}

[gke]
regions = ["us-west4"]
