[serviceweaver]
binary = "./us_deployment"

[single]
listeners.post_notification = {address = "0.0.0.0:12345"}
antipodeAgents.clientRedis = {datastoreType = "MySQL", host = "{{ host_us }}", port = "3308", user = "root", password = "root_password", datastore = "post_notification"}
antipodeAgents.clientRabbitMQ = {datastoreType = "RabbitMQ", host = "{{ host_us }}", port = "5673", user = "admin", password = "admin", datastore = "rabbitMQ"}

[multi]
listeners.post_notification = {address = "0.0.0.0:12345"}
antipodeAgents.clientRedis = {datastoreType = "MySQL", host = "{{ host_us }}", port = "3308", user = "root", password = "root_password", datastore = "post_notification"}
antipodeAgents.clientRabbitMQ = {datastoreType = "RabbitMQ", host = "{{ host_us }}", port = "5673", user = "admin", password = "admin", datastore = "rabbitMQ"}

[gke]
regions = ["us-west4"]
