---
- hosts: 
    trainticket-wrk2
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Create app directory
      file:
        path: "/home/{{ hostvars[inventory_hostname]['user'] }}/{{ app_folder_name }}"
        state: directory

# -----------
# APPLICATION
# -----------
- hosts: 
    trainticket-wrk2
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Create dependencies script in app node
      copy:
        src: "{{ base_dir }}/deploy/scripts/deps-app.sh"
        dest: "/home/{{ hostvars[inventory_hostname]['user'] }}/"
        mode: u=rwx,g=rx,o=rx # 755 permissions

    - name: Install dependencies in app node
      shell: ./deps-app.sh
      args:
        executable: /bin/bash

    - name: Copy manager.py script, requirements.txt and gcp folder to app wrk2 node
      copy:
        src: "{{ item }}"
        dest: /home/{{ hostvars[inventory_hostname]['user'] }}/{{ app_folder_name }}/
        mode: u=rwx,g=rx,o=rx # 755 permissions
      with_items:
        - "{{ base_dir }}/manager.py"
        - "{{ base_dir }}/requirements.txt"
        - "{{ base_dir }}/gcp"

    - name: Install python requirements
      shell: pip3 install -r requirements.txt
      args:
        chdir: "{{ app_folder_name }}"