---
- hosts: trainticket-app
  gather_facts: no
  any_errors_fatal: true
  tasks:

    - name: Build trainticket in app service node
      shell: /usr/local/go/bin/go build
      args:
        chdir: "{{ app_folder_name }}"
        executable: /bin/bash

    - name: Start trainticket in app service node
      shell: >
        /usr/bin/tmux new-session -s trainticket -d \
          "$HOME/go/bin/weaver multi deploy weaver-gcp.toml"
      args:
        chdir: "{{ app_folder_name }}"
        executable: /bin/bash

    - name: Verify if trainticket is running in app service node
      wait_for:
        host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        port: "{{ hostvars[inventory_hostname]['app_port'] | int }}"
        state: started
        timeout: 30