["eu-deployment/Notifier"]
rabbitmq_address    = "34.65.41.16"
rabbitmq_port       = "5672"
rabbitmq_user    = "admin"
rabbitmq_password       = "admin"

["eu-deployment/PostStorageEu"]
redis_address       = "34.65.41.16"
redis_port          = "6381"
redis_password          = ""

[serviceweaver]
binary = "./eu-deployment"

[single]
listeners.postnot = {address = "0.0.0.0:12345"}

[multi]
listeners.postnot = {address = "0.0.0.0:12345"}

[gke]
regions = ["europe-west6"]
listeners.postnot = {public_hostname = "hello.com"}
