["us_deployment/pkg/services/SocialGraphService"]
mongodb_address = "34.27.101.47"
redis_address = "34.27.101.47"
redis_port = 6384
mongodb_port = 27017
region = "europe-west3"

["us_deployment/pkg/services/UserService"]
mongodb_address = "34.27.101.47"
memcached_address = "34.27.101.47"
mongodb_port = 27017
memcached_port = 11214
region = "europe-west3"

["us_deployment/pkg/services/WriteHomeTimelineService"]
rabbitmq_address = "34.27.101.47"
mongodb_address = "34.27.101.47"
redis_address = "34.27.101.47"
mongodb_port = 27018
redis_port = 6386
rabbitmq_port = 5673
num_workers = 16
region = "us-central1"

["us_deployment/pkg/services/UpdateHomeTimelineService"]
rabbitmq_address = "34.27.101.47"
mongodb_address = "34.27.101.47"
redis_address = "34.27.101.47"
mongodb_port = 27018
redis_port = 6386
rabbitmq_port = 5673
num_workers = 1
region = "us-central1"

["github.com/ServiceWeaver/weaver/Main"]
region = "europe-west3"

[serviceweaver]
binary = "./us_deployment"
name = "us_deployment"

[gke]
regions = [ "europe-west3",]

[single.listeners.socialnetwork]
address = "0.0.0.0:12345"

[multi.listeners.socialnetwork]
address = "0.0.0.0:12345"

[gke.listeners.wrk2]
public_hostname = "weaver.dsb.socialnetwork.eu"
