["eu_deployment/pkg/services/ComposePostService"]
redis_address = "34.159.213.168"
rabbitmq_address = "34.159.213.168"
redis_port = 6381
rabbitmq_port = 5672
region = "europe-west3"
regions = [ "us-central1",]

["eu_deployment/pkg/services/HomeTimelineService"]
redis_address = "34.159.213.168"
redis_port = 6382
region = "europe-west3"

["eu_deployment/pkg/services/PostStorageService"]
mongodb_address = "34.159.213.168"
memcached_address = "34.159.213.168"
mongodb_port = 27017
memcached_port = 11212
region = "europe-west3"

["eu_deployment/pkg/services/SocialGraphService"]
mongodb_address = "34.159.213.168"
redis_address = "34.159.213.168"
redis_port = 6384
mongodb_port = 27017
region = "europe-west3"

["eu_deployment/pkg/services/UrlShortenService"]
mongodb_address = "34.159.213.168"
memcached_address = "34.159.213.168"
mongodb_port = 27017
memcached_port = 11213
region = "europe-west3"

["eu_deployment/pkg/services/UserService"]
mongodb_address = "34.159.213.168"
memcached_address = "34.159.213.168"
mongodb_port = 27017
memcached_port = 11214
region = "europe-west3"

["eu_deployment/pkg/services/UserMentionService"]
mongodb_address = "34.159.213.168"
memcached_address = "34.159.213.168"
mongodb_port = 27017
memcached_port = 11214
region = "europe-west3"

["eu_deployment/pkg/services/UserTimelineService"]
mongodb_address = "34.159.213.168"
redis_address = "34.159.213.168"
mongodb_port = 27017
redis_port = 6383
region = "europe-west3"

["eu_deployment/pkg/services/MediaService"]
region = "europe-west3"

["eu_deployment/pkg/services/TextService"]
region = "europe-west3"

["eu_deployment/pkg/services/UniqueIdService"]
region = "europe-west3"

["github.com/ServiceWeaver/weaver/Main"]
region = "europe-west3"

[serviceweaver]
binary = "./eu_deployment"
name = "eu_deployment"

[gke]
regions = [ "europe-west3",]

[single.listeners.wrk2]
address = "0.0.0.0:12345"

[multi.listeners.wrk2]
address = "0.0.0.0:12345"

[gke.listeners.wrk2]
public_hostname = "weaver.dsb.socialnetwork.eu"
