appConfig: weaver-local.toml
repo: docker.io/tiagomalhadas

ScalingSpec:
  minReplicas: 1
  maxReplicas: 1

listeners:
  - name: wrk2
    public: true
    port: 12345

resourceSpec:
  requests:
    memory: "10Gi"
    cpu: "2"  
  limits:
    memory: "32Gi"
    cpu: "8"  