["eu_deployment/Notifier"]
rabbitmq_address = "34.89.156.15"
rabbitmq_port = "5672"
rabbitmq_user = "admin"
rabbitmq_password = "admin"

["eu_deployment/Post_storage_europe"]
mongo_address = "34.89.156.15"
mongo_port = "27017"

[serviceweaver]
binary = "./eu_deployment"

[gke]
regions = [ "europe-west6",]

[single.listeners.post_notification]
address = "0.0.0.0:12345"

[multi.listeners.post_notification]
address = "0.0.0.0:12345"

[gke.listeners.post_notification]
public_hostname = "hello.com"
