# --------
# Services
# --------

["eu_deployment/pkg/services/ComposePostService"]
redis_address       = "{{ host_eu }}"
redis_port          = 6381
region              = "europe-west3"
regions             = ["europe-west3", "us-central1"]

["eu_deployment/pkg/services/HomeTimelineService"]
redis_address       = "{{ host_eu }}"
redis_port          = 6382
region              = "europe-west3"

["eu_deployment/pkg/services/PostStorageService"]
mongodb_address     = "{{ host_eu }}"
memcached_address   = "{{ host_eu }}"
mongodb_port        = 27017
memcached_port      = 11212
region              = "europe-west3"

["eu_deployment/pkg/services/SocialGraphService"]
mongodb_address     = "{{ host_eu }}"
redis_address       = "{{ host_eu }}"
redis_port          = 6384
mongodb_port        = 27017
region              = "europe-west3"

["eu_deployment/pkg/services/UrlShortenService"]
mongodb_address     = "{{ host_eu }}"
memcached_address   = "{{ host_eu }}"
mongodb_port        = 27017
memcached_port      = 11213
region              = "europe-west3"

["eu_deployment/pkg/services/UserService"]
mongodb_address     = "{{ host_eu }}"
memcached_address   = "{{ host_eu }}"
mongodb_port        = 27017
memcached_port      = 11214
region              = "europe-west3"

["eu_deployment/pkg/services/UserMentionService"]
# uses UserService cache (memcached)
mongodb_address     = "{{ host_eu }}"
memcached_address   = "{{ host_eu }}"
mongodb_port        = 27017
memcached_port      = 11214
region              = "europe-west3"

["eu_deployment/pkg/services/UserTimelineService"]
mongodb_address     = "{{ host_eu }}"
redis_address       = "{{ host_eu }}"
mongodb_port        = 27017
redis_port          = 6383
region              = "europe-west3"

["eu_deployment/pkg/services/MediaService"]
region              = "europe-west3"

["eu_deployment/pkg/services/TextService"]
region              = "europe-west3"

["eu_deployment/pkg/services/UniqueIdService"]
region              = "europe-west3"

# wrk2 api
["github.com/ServiceWeaver/weaver/Main"]
region              = "europe-west3"

# ----------
# Deployment
# ----------

[single]
listeners.wrk2 = {address = "0.0.0.0:12345"}
antipodeAgents.rabbitClientWriteHomeTL = {datastoreType = "RabbitMQ", host = "{{ host_eu }}", port = "5673", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "write-home-timeline"}
antipodeAgents.rabbitClientCompose = {datastoreType = "RabbitMQ", host = "{{ host_eu }}", port = "5672", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "write-home-timeline"}
antipodeAgents.rabbitClientUpdateHomeTL = {datastoreType = "RabbitMQ", host = "{{ host_eu }}", port = "5673", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "update-home-timeline"}
antipodeAgents.mongoClientPostStorage = {datastoreType = "MongoDB", host = "{{ host_eu }}", port = "27017", datastore = "post-storage"}
antipodeAgents.mongoClientWriteHomeTL = {datastoreType = "MongoDB", host = "{{ host_eu }}", port = "27018", datastore = "post-storage"}
antipodeAgents.mongoClientUpdateHomeTL = {datastoreType = "MongoDB", host = "{{ host_eu }}", port = "27018", datastore = "post-storage"}

[multi]
listeners.wrk2 = {address = "0.0.0.0:12345"}
antipodeAgents.rabbitClientWriteHomeTL = {datastoreType = "RabbitMQ", host = "{{ host_eu }}", port = "5673", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "write-home-timeline"}
antipodeAgents.rabbitClientCompose = {datastoreType = "RabbitMQ", host = "{{ host_eu }}", port = "5672", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "write-home-timeline"}
antipodeAgents.rabbitClientUpdate = {datastoreType = "RabbitMQ", host = "{{ host_eu }}", port = "5672", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "update-home-timeline"}
antipodeAgents.rabbitClientUpdateHomeTL = {datastoreType = "RabbitMQ", host = "{{ host_eu }}", port = "5673", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "update-home-timeline"}
antipodeAgents.mongoClientPostStorage = {datastoreType = "MongoDB", host = "{{ host_eu }}", port = "27017", datastore = "post-storage"}
antipodeAgents.mongoClientWriteHomeTL = {datastoreType = "MongoDB", host = "{{ host_eu }}", port = "27018", datastore = "post-storage"}
antipodeAgents.mongoClientUpdateHomeTL = {datastoreType = "MongoDB", host = "{{ host_eu }}", port = "27018", datastore = "post-storage"}


[serviceweaver]
binary = "./eu_deployment"
name = "eu_deployment"

[gke]
regions = ["europe-west3"]
listeners.wrk2 = {public_hostname = "weaver.dsb.socialnetwork.eu"}
