["us_deployment/Notifier"]
rabbitmq_address    = "localhost"
rabbitmq_port       = "5673"
rabbitmq_user    = "admin"
rabbitmq_password       = "admin"

["us_deployment/Post_storage_america"]
mysql_address       = "127.0.0.1"
mysql_port          = "3308"
mysql_password          = "root_password"
mysql_user          = "root"
mysql_datastore          = "post_notification"


[serviceweaver]
binary = "./us_deployment"

[single]
listeners.post_notification = {address = "0.0.0.0:12345"}

[multi]
listeners.post_notification = {address = "0.0.0.0:12345"}

[gke]
regions = ["us-west4"]
