["us-deployment/Notifier"]
rabbitmq_address    = "34.171.188.100"
rabbitmq_port       = "5673"
rabbitmq_user    = "admin"
rabbitmq_password       = "admin"

["us-deployment/PostStorageUs"]
mysql_address       = "34.171.188.100"
mysql_port          = "3308"
mysql_password          = "root_password"
mysql_user          = "root"
mysql_datastore          = "post_notification"


[serviceweaver]
binary = "./us-deployment"

[single]
listeners.postnot = {address = "0.0.0.0:12346"}

[multi]
listeners.postnot = {address = "0.0.0.0:12346"}

[gke]
regions = ["us-west4"]
listeners.postnot = {public_hostname = "hello.com"}
