["eu-deployment/Notifier"]
rabbitmq_address    = "34.65.41.16"
rabbitmq_port       = "5672"
rabbitmq_user    = "admin"
rabbitmq_password       = "admin"

["eu-deployment/PostStorageEu"]
mongo_address       = "34.65.41.16"
mongo_port          = "27017"


[serviceweaver]
binary = "./eu-deployment"

[single]
listeners.postnot = {address = "0.0.0.0:12345"}

[multi]
listeners.postnot = {address = "0.0.0.0:12345"}


[gke]
regions = ["europe-west6"]
listeners.postnot = {public_hostname = "hello.com"}
