["us_deployment/Notifier"]
rabbitmq_address = "104.197.49.4"
rabbitmq_port = "5673"
rabbitmq_user = "admin"
rabbitmq_password = "admin"

["us_deployment/Post_storage_america"]
redis_address = "104.197.49.4"
redis_port = "6381"
redis_password = ""

[serviceweaver]
binary = "./us_deployment"

[gke]
regions = [ "us-west4",]

[single.listeners.post_notification]
address = "0.0.0.0:12345"

[multi.listeners.post_notification]
address = "0.0.0.0:12345"
