version: '3.7'
services:
  # ------------
  # Post-Storage: MONGO
  # ------------
  ts-user-mongo:
    image: mongo:4.4
    container_name: ts-user-mongo
    hostname: ts-user-mongo
    ports:
      - "27017:27017"
    cap_add:
      - NET_ADMIN
  ts-auth-mongo:
    image: mongo:4.4
    container_name: ts-auth-mongo
    hostname: ts-auth-mongo
    ports:
      - "27018:27017"
    cap_add:
      - NET_ADMIN
  ts-train-mongo:
    image: mongo:4.4
    container_name: ts-train-mongo
    hostname: ts-train-mongo
    ports:
      - "27019:27017"
    cap_add:
      - NET_ADMIN
  ts-price-mongo:
    image: mongo:4.4
    container_name: ts-price-mongo
    hostname: ts-price-mongo
    ports:
      - "27020:27017"
    cap_add:
      - NET_ADMIN
  ts-order-mongo:
    image: mongo:4.4
    container_name: ts-order-mongo
    hostname: ts-order-mongo
    ports:
      - "27021:27017"
    cap_add:
      - NET_ADMIN
  ts-payment-mongo:
    image: mongo:4.4
    container_name: ts-payment-mongo
    hostname: ts-payment-mongo
    ports:
      - "27022:27017"
    cap_add:
      - NET_ADMIN
  ts-inside-payment-mongo:
    image: mongo:4.4
    container_name: ts-inside-payment-mongo
    hostname: ts-inside-payment-mongo
    ports:
      - "27023:27017"
    cap_add:
      - NET_ADMIN
  ts-contacts-mongo:
    image: mongo:4.4
    container_name: ts-contacts-mongo
    hostname: ts-contacts-mongo
    ports:
      - "27024:27017"
    cap_add:
      - NET_ADMIN

  
