[serviceweaver]
binary = "./eu_deployment"

[single]
listeners.post_notification = {address = "0.0.0.0:12345"}
antipodeAgents.clientRedis = {datastoreType = "Redis", host = "localhost", port = "6379", password = "", datastore = "posts"}
antipodeAgents.clientRabbitMQ = {datastoreType = "RabbitMQ", host = "localhost", port = "5672", user = "admin", password = "admin", datastore = "rabbitMQ"}

[multi]
listeners.post_notification = {address = "0.0.0.0:12345"}
antipodeAgents.clientRedis = {datastoreType = "Redis", host = "localhost", port = "6379", password = "", datastore = "posts"}
antipodeAgents.clientRabbitMQ = {datastoreType = "RabbitMQ", host = "localhost", port = "5672", user = "admin", password = "admin", datastore = "rabbitMQ"}

[gke]
regions = ["europe-west6"]
listeners.post_notification = {public_hostname = "hello.com"}
